apiVersion: v1
kind: ConfigMap
metadata:
  name: gcs-mounts
data:
  gcs-mounts.sh: |-
    #!/bin/bash
    {{ range $item, $user := .Values.users -}}
    runuser -l {{ $user.user }} -c \
      {{- if $user.onlyDir }}
      'export GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcloud-key.json; gcsfuse --only-dir {{ $user.onlyDir }} {{ $user.bucket }} /home/{{ $user.user }}/ftp'
      {{ else }}
      'export GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcloud-key.json; gcsfuse {{ $user.bucket }} /home/{{ $user.user }}/ftp'
      {{- end }}
    {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users
data:
  users.conf: |-
    {{- range $item, $user := .Values.users }}
    {{ printf " %s:%s:::ftp" $user.user $user.password -}}
    {{ end }}
