{{ if .Values.gcloud_key_base64 }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sftp-gcloud-key
data:
  gcloud-key.json: {{ .Values.gcloud_key_base64 }}
{{ end }}
{{ if .Values.ssh_private_key_base64 }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: ssh-secret-key
data:
  ssh_host_rsa_key: {{ .Values.ssh_private_key_base64 }}
{{ end }}
