apiVersion: v1
name: k8s-sftp-gcs
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
annotations:
  artifacthub.io/links: |
    - name: homelink
      url: https://github.com/danuk/k8s-sftp-gcs
  artifacthub.io/maintainers: |
    - name: danuk
      email: mail@danuk.ru
